"""
AgentPulse MCP Server — exposes live eval data as tools for Claude Code.

Tools
-----
get_recommendations()          Latest HIGH/MEDIUM/INFO findings
get_failing_metrics()          Metrics below SLA with gap analysis
list_recent_runs(limit)        Recent evaluated runs with quality scores
get_run_details(run_id)        Per-run scores + LLM reasons

Transport: stdio (Claude Code spawns this as a subprocess automatically).
"""

import json
import os
import sys
import tempfile
from pathlib import Path

# Resolve project root so sqlite:///mlflow.db finds the right file regardless
# of which directory Claude Code spawns us from.
_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

import mlflow
from mlflow.tracking import MlflowClient
from mcp.server.fastmcp import FastMCP

_TRACKING_URI = f"sqlite:///{_ROOT / 'mlflow.db'}"
_AGENT_EXP    = "it-helpdesk-agent-evals"
_SUMMARY_EXP  = "it-helpdesk-eval-summary"

_SLA = {
    "contextual_relevancy": 0.70,
    "faithfulness":         0.70,
    "answer_relevancy":     0.70,
    "completeness":         0.60,
    "actionability":        0.60,
    "professional_tone":    0.60,
    "task_resolution":      0.60,
    "quality_score":        0.65,
    "rag_score":            0.70,
    "helpdesk_score":       0.60,
    "safety_score":         0.90,
}

mcp = FastMCP("AgentPulse")


def _client() -> MlflowClient:
    mlflow.set_tracking_uri(_TRACKING_URI)
    return MlflowClient(tracking_uri=_TRACKING_URI)


def _download_artifact(run_id: str, filename: str) -> dict:
    client = _client()
    with tempfile.TemporaryDirectory() as tmpdir:
        local = client.download_artifacts(run_id, filename, dst_path=tmpdir)
        with open(local, encoding="utf-8") as f:
            return json.load(f)


# ── Tools ─────────────────────────────────────────────────────────────────────

@mcp.tool()
def get_recommendations() -> str:
    """
    Return the latest prioritised eval recommendations (HIGH / MEDIUM / INFO)
    generated by AgentPulse eval_runner. Each recommendation includes:
    category, severity, finding, affected_metric, current_score, sla_threshold,
    and suggested_action.

    Run eval_runner.py first if no data is returned.
    """
    client = _client()
    exp = mlflow.get_experiment_by_name(_SUMMARY_EXP)
    if exp is None:
        return "No eval summary experiment found. Run: python -m evals.eval_runner"

    runs = client.search_runs(
        [exp.experiment_id],
        order_by=["start_time DESC"],
        max_results=1,
    )
    if not runs:
        return "No summary runs found. Run: python -m evals.eval_runner"

    run_id = runs[0].info.run_id
    try:
        data = _download_artifact(run_id, "eval_recommendations.json")
        return json.dumps(data, indent=2, ensure_ascii=False)
    except Exception as exc:
        return f"Could not load recommendations artifact: {exc}"


@mcp.tool()
def get_failing_metrics() -> str:
    """
    Return every metric currently averaging below its SLA threshold across the
    last 50 evaluated runs. Each entry includes: metric name, average score,
    SLA threshold, gap (sla - average), and run count.

    Sorted by gap descending — largest failures first.
    """
    client = _client()
    exp = mlflow.get_experiment_by_name(_AGENT_EXP)
    if exp is None:
        return "No agent experiment found."

    runs = client.search_runs(
        [exp.experiment_id],
        filter_string="metrics.quality_score > 0",
        order_by=["start_time DESC"],
        max_results=50,
    )
    if not runs:
        return "No scored runs found. Run eval_runner.py first."

    totals: dict[str, float] = {}
    counts: dict[str, int]   = {}
    for run in runs:
        for metric in _SLA:
            v = run.data.metrics.get(metric)
            if v is not None:
                totals[metric] = totals.get(metric, 0.0) + v
                counts[metric] = counts.get(metric, 0) + 1

    failing = []
    passing = []
    for metric, sla in _SLA.items():
        if metric not in totals:
            continue
        avg = totals[metric] / counts[metric]
        entry = {
            "metric":          metric,
            "average":         round(avg, 3),
            "sla":             sla,
            "gap":             round(sla - avg, 3),
            "runs_evaluated":  counts[metric],
        }
        (failing if avg < sla else passing).append(entry)

    failing.sort(key=lambda x: x["gap"], reverse=True)
    return json.dumps(
        {
            "failing_count": len(failing),
            "passing_count": len(passing),
            "total_runs_analyzed": len(runs),
            "failing": failing,
            "passing": [p["metric"] for p in passing],
        },
        indent=2,
    )


@mcp.tool()
def list_recent_runs(limit: int = 10) -> str:
    """
    List the most recent evaluated agent runs with headline quality metrics.
    Returns: run_id, query, intent, quality_score, rag_score, helpdesk_score,
    contextual_relevancy, latency_total_pipeline.

    Use run_id from this output to call get_run_details().
    """
    client = _client()
    exp = mlflow.get_experiment_by_name(_AGENT_EXP)
    if exp is None:
        return "No agent experiment found."

    runs = client.search_runs(
        [exp.experiment_id],
        filter_string="metrics.quality_score > 0",
        order_by=["start_time DESC"],
        max_results=max(1, min(limit, 100)),
    )

    result = []
    for run in runs:
        m = run.data.metrics
        result.append({
            "run_id":               run.info.run_id,
            "query":                run.data.tags.get("mlflow.runName", run.info.run_id),
            "intent":               m.get("intent_confidence") and run.data.params.get("intent", "unknown"),
            "quality_score":        m.get("quality_score"),
            "rag_score":            m.get("rag_score"),
            "helpdesk_score":       m.get("helpdesk_score"),
            "contextual_relevancy": m.get("contextual_relevancy"),
            "latency_ms":           round(m.get("latency_total_pipeline", 0) * 1000),
        })

    return json.dumps({"run_count": len(result), "runs": result}, indent=2)


@mcp.tool()
def get_run_details(run_id: str) -> str:
    """
    Get full per-run eval scores AND the LLM-generated reason string for every
    metric for a specific run. The reasons explain WHY each metric scored as it
    did — essential for understanding what the agent got right or wrong.

    Pass a run_id from list_recent_runs().
    """
    try:
        data = _download_artifact(run_id, "eval_reasons.json")
        return json.dumps(data, indent=2, ensure_ascii=False)
    except Exception:
        pass

    # Fall back to raw MLflow metrics if artifact is missing
    try:
        client = _client()
        run = client.get_run(run_id)
        return json.dumps(
            {
                "run_id": run_id,
                "note": "eval_reasons.json artifact not found — showing raw metrics only",
                "metrics": run.data.metrics,
                "params":  run.data.params,
                "tags":    run.data.tags,
            },
            indent=2,
        )
    except Exception as exc:
        return f"Could not load run {run_id}: {exc}"


if __name__ == "__main__":
    mcp.run()
